### ISSUE TITLE
Not able to use the update sites from Eclipse Mars

### ISSUE THREAD

**Issue by hrj** [spring-projects/eclipse-integration-commons#12]
I tried all the following URLs:
```
http://dist.springsource.com/release/TOOLS/eclipse-integration-commons/
http://dist.springsource.com/snapshot/TOOLS/eclipse-integration-commons/nightly/e4.4 
http://dist.springsource.com/milestone/TOOLS/eclipse-integration-commons/e4.4
http://dist.springsource.com/release/TOOLS/eclipse-integration-commons/e4.4
```

But Eclipse either shows an empty list or gives the following error:
```
No software site found at http://dist.springsource.com/release/TOOLS/eclipse-integration-commons/e4.4. Do you wish to edit the location?
```

**Comment by hrj** [comment]
Trying to access any of the `dist.springsource.com` URL through browser returns an XML file with access denied response.
For example, accessing `http://dist.springsource.com/` gives me:
```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>9C0C667C4526B9F0</RequestId>
  <HostId>/Uarl1EVJYp3juvFqPiuieNVit21NV5feVjUihoqTRDLsnVGBWYbYGBQDBbAn0RcPDaH6azkzdg=</HostId>
</Error>
```

**Comment by martinlippert** [comment]
There was an issue with the composite update site. This one should work now:
http://dist.springsource.com/release/TOOLS/eclipse-integration-commons/

As a side note: This URL is not meant to be used via a browser. It doesn't serve an index page and therefore returns the AccessDenied XML. But you can use it inside of Eclipse via the "Install New Software" dialog. That works.
