### ISSUE TITLE
is there a way to include in quick search also "derived resources"

### ISSUE THREAD

**Issue by ghost** [spring-projects/eclipse-integration-commons#28]
is there a way to include in quick search also "derived resources" like "open resource" has?
![BmPrr6ATtA](https://user-images.githubusercontent.com/58207906/72500701-ceafa700-383d-11ea-955d-146bb23d6c8f.jpg)

thanks

**Comment by martinlippert** [comment]
The quick search feature got contributed to the Eclipse platform project. Please file enhancement requests for it via: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform
