### ISSUE TITLE
Make Quick Search dialog not modal

### ISSUE THREAD

**Issue by paulvi** [spring-projects/eclipse-integration-commons#6]
in Quick Search for Eclipse http://marketplace.eclipse.org/content/quick-search-eclipse
please make dialog not modal (and not close by default), 
just like <kbd>Ctrl+F</kbd> in Eclipse or MS Word.

Also could it have option to push results to Eclipse Search View ?

**Comment by spudtheimpaler** [comment]
@kdvolder The Jira issue to which you linked can not be commented on, so I will comment here.

Personally I understand the downsides to modality, but for what this is used for I can't see a better alternative to use in a view. Personally I am happy for it to be left how it is.

**Comment by kdvolder** [comment]
We finally did this :-) But looks like we have this older issue still floating around.

See: https://github.com/spring-projects/sts4/issues/189
